// <auto-generated />
using System;
using AiWearStudio.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiWearStudio.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260508200347_InitialCatalogSchema")]
    partial class InitialCatalogSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiWearStudio.Catalog.Domain.Entities.Garment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("garments", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000001"),
                            Category = "camiseta",
                            DisplayOrder = 1,
                            Name = "Camiseta Manga Corta"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000002"),
                            Category = "camiseta",
                            DisplayOrder = 2,
                            Name = "Camiseta Manga Larga"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000003"),
                            Category = "polo",
                            DisplayOrder = 3,
                            Name = "Polo / Piqué"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000004"),
                            Category = "buzo",
                            DisplayOrder = 4,
                            Name = "Buzo Crew Neck"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000005"),
                            Category = "buzo",
                            DisplayOrder = 5,
                            Name = "Buzo con Capucha"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000006"),
                            Category = "chaqueta",
                            DisplayOrder = 6,
                            Name = "Chaqueta Deportiva"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000007"),
                            Category = "pantalon",
                            DisplayOrder = 7,
                            Name = "Pantalón de Buzo"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000008"),
                            Category = "short",
                            DisplayOrder = 8,
                            Name = "Short Deportivo"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000009"),
                            Category = "accesorio",
                            DisplayOrder = 9,
                            Name = "Gorra 5 Paneles"
                        },
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000010"),
                            Category = "accesorio",
                            DisplayOrder = 10,
                            Name = "Tote Bag"
                        });
                });

            modelBuilder.Entity("AiWearStudio.Catalog.Domain.Entities.GarmentColorVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GarmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.HasKey("Id");

                    b.HasIndex("GarmentId");

                    b.ToTable("garment_color_variants", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0000001-0001-0001-0001-000000000001"),
                            ColorName = "Blanco",
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            HexCode = "#FFFFFF"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0001-0001-0001-000000000002"),
                            ColorName = "Negro",
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            HexCode = "#000000"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0001-0001-0001-000000000003"),
                            ColorName = "Gris",
                            DisplayOrder = 3,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            HexCode = "#808080"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0001-0001-0001-000000000004"),
                            ColorName = "Azul Navy",
                            DisplayOrder = 4,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            HexCode = "#001F5B"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0001-0001-0001-000000000005"),
                            ColorName = "Rojo",
                            DisplayOrder = 5,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            HexCode = "#CC0000"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0002-0002-0002-000000000001"),
                            ColorName = "Blanco",
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000002"),
                            HexCode = "#FFFFFF"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0002-0002-0002-000000000002"),
                            ColorName = "Negro",
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000002"),
                            HexCode = "#000000"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0002-0002-0002-000000000003"),
                            ColorName = "Gris",
                            DisplayOrder = 3,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000002"),
                            HexCode = "#808080"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0002-0002-0002-000000000004"),
                            ColorName = "Azul Navy",
                            DisplayOrder = 4,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000002"),
                            HexCode = "#001F5B"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0003-0003-0003-000000000001"),
                            ColorName = "Blanco",
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000003"),
                            HexCode = "#FFFFFF"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0003-0003-0003-000000000002"),
                            ColorName = "Negro",
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000003"),
                            HexCode = "#000000"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0003-0003-0003-000000000003"),
                            ColorName = "Azul Navy",
                            DisplayOrder = 3,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000003"),
                            HexCode = "#001F5B"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0003-0003-0003-000000000004"),
                            ColorName = "Verde Bosque",
                            DisplayOrder = 4,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000003"),
                            HexCode = "#228B22"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0004-0004-0004-000000000001"),
                            ColorName = "Gris Claro",
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000004"),
                            HexCode = "#D3D3D3"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0004-0004-0004-000000000002"),
                            ColorName = "Negro",
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000004"),
                            HexCode = "#000000"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0004-0004-0004-000000000003"),
                            ColorName = "Azul Navy",
                            DisplayOrder = 3,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000004"),
                            HexCode = "#001F5B"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0004-0004-0004-000000000004"),
                            ColorName = "Beige",
                            DisplayOrder = 4,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000004"),
                            HexCode = "#F5F5DC"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0005-0005-0005-000000000001"),
                            ColorName = "Gris Claro",
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000005"),
                            HexCode = "#D3D3D3"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0005-0005-0005-000000000002"),
                            ColorName = "Negro",
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000005"),
                            HexCode = "#000000"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0005-0005-0005-000000000003"),
                            ColorName = "Azul Navy",
                            DisplayOrder = 3,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000005"),
                            HexCode = "#001F5B"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0005-0005-0005-000000000004"),
                            ColorName = "Verde Militar",
                            DisplayOrder = 4,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000005"),
                            HexCode = "#4B5320"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0006-0006-0006-000000000001"),
                            ColorName = "Negro",
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000006"),
                            HexCode = "#000000"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0006-0006-0006-000000000002"),
                            ColorName = "Azul Navy",
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000006"),
                            HexCode = "#001F5B"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0006-0006-0006-000000000003"),
                            ColorName = "Verde Militar",
                            DisplayOrder = 3,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000006"),
                            HexCode = "#4B5320"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0007-0007-0007-000000000001"),
                            ColorName = "Gris",
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000007"),
                            HexCode = "#808080"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0007-0007-0007-000000000002"),
                            ColorName = "Negro",
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000007"),
                            HexCode = "#000000"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0007-0007-0007-000000000003"),
                            ColorName = "Azul Navy",
                            DisplayOrder = 3,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000007"),
                            HexCode = "#001F5B"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0008-0008-0008-000000000001"),
                            ColorName = "Negro",
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000008"),
                            HexCode = "#000000"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0008-0008-0008-000000000002"),
                            ColorName = "Azul Navy",
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000008"),
                            HexCode = "#001F5B"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0008-0008-0008-000000000003"),
                            ColorName = "Rojo",
                            DisplayOrder = 3,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000008"),
                            HexCode = "#CC0000"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0009-0009-0009-000000000001"),
                            ColorName = "Negro",
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000009"),
                            HexCode = "#000000"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0009-0009-0009-000000000002"),
                            ColorName = "Azul Navy",
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000009"),
                            HexCode = "#001F5B"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0009-0009-0009-000000000003"),
                            ColorName = "Blanco",
                            DisplayOrder = 3,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000009"),
                            HexCode = "#FFFFFF"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0010-0010-0010-000000000001"),
                            ColorName = "Beige",
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000010"),
                            HexCode = "#F5F5DC"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0010-0010-0010-000000000002"),
                            ColorName = "Negro",
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000010"),
                            HexCode = "#000000"
                        },
                        new
                        {
                            Id = new Guid("e0000001-0010-0010-0010-000000000003"),
                            ColorName = "Blanco",
                            DisplayOrder = 3,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000010"),
                            HexCode = "#FFFFFF"
                        });
                });

            modelBuilder.Entity("AiWearStudio.Catalog.Domain.Entities.GarmentView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GarmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ViewName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("GarmentId");

                    b.ToTable("garment_views", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000001"),
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            ViewName = "front"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000002"),
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            ViewName = "back"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000003"),
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000002"),
                            ViewName = "front"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000004"),
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000002"),
                            ViewName = "back"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000005"),
                            DisplayOrder = 3,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000002"),
                            ViewName = "sleeve_left"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000006"),
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000003"),
                            ViewName = "front"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000007"),
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000003"),
                            ViewName = "back"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000008"),
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000004"),
                            ViewName = "front"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000009"),
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000004"),
                            ViewName = "back"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000010"),
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000005"),
                            ViewName = "front"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000011"),
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000005"),
                            ViewName = "back"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000012"),
                            DisplayOrder = 3,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000005"),
                            ViewName = "hood"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000013"),
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000006"),
                            ViewName = "front"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000014"),
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000006"),
                            ViewName = "back"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000015"),
                            DisplayOrder = 3,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000006"),
                            ViewName = "sleeve_left"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000016"),
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000007"),
                            ViewName = "front"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000017"),
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000007"),
                            ViewName = "back"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000018"),
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000008"),
                            ViewName = "front"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000019"),
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000008"),
                            ViewName = "back"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000020"),
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000009"),
                            ViewName = "front"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000021"),
                            DisplayOrder = 2,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000009"),
                            ViewName = "side_left"
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000022"),
                            DisplayOrder = 1,
                            GarmentId = new Guid("b0000001-0000-0000-0000-000000000010"),
                            ViewName = "front"
                        });
                });

            modelBuilder.Entity("AiWearStudio.Catalog.Domain.Entities.PrintTechnique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("print_techniques", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            Description = "Impresión por calor con tinta de sublimación. Ideal para prendas de poliéster con cobertura total.",
                            Name = "Sublimación Total"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000002"),
                            Description = "Impresión con malla y tinta plastisol. Máxima durabilidad para pedidos de volumen.",
                            Name = "Serigrafía"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000003"),
                            Description = "Film transferible por calor. Permite colores ilimitados y detalles finos.",
                            Name = "Transfer Digital (DTF)"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000004"),
                            Description = "Hilo bordado sobre la prenda. Acabado premium de alta durabilidad.",
                            Name = "Bordado"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000005"),
                            Description = "Vinilo cortado y aplicado con calor. Ideal para textos y formas simples.",
                            Name = "Vinilo Termoadhesivo"
                        });
                });

            modelBuilder.Entity("AiWearStudio.Catalog.Domain.Entities.PrintZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GarmentViewId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RecommendedTechniqueId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WidthCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("XCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("YCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("GarmentViewId");

                    b.HasIndex("RecommendedTechniqueId");

                    b.ToTable("print_zones", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000001"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000001"),
                            HeightCm = 18m,
                            Name = "Pecho Central",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000002"),
                            WidthCm = 15m,
                            XCm = 8m,
                            YCm = 7m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000002"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000002"),
                            HeightCm = 26m,
                            Name = "Espalda Completa",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000002"),
                            WidthCm = 26m,
                            XCm = 5m,
                            YCm = 6m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000003"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000003"),
                            HeightCm = 18m,
                            Name = "Pecho Central",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000002"),
                            WidthCm = 15m,
                            XCm = 8m,
                            YCm = 7m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000004"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000004"),
                            HeightCm = 26m,
                            Name = "Espalda Completa",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000002"),
                            WidthCm = 26m,
                            XCm = 5m,
                            YCm = 6m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000005"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000005"),
                            HeightCm = 8m,
                            Name = "Logo Manga",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000003"),
                            WidthCm = 8m,
                            XCm = 2m,
                            YCm = 5m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000006"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000006"),
                            HeightCm = 10m,
                            Name = "Pecho Izquierdo",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000004"),
                            WidthCm = 10m,
                            XCm = 6m,
                            YCm = 7m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000007"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000006"),
                            HeightCm = 10m,
                            Name = "Pecho Derecho",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000004"),
                            WidthCm = 10m,
                            XCm = 14m,
                            YCm = 7m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000008"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000007"),
                            HeightCm = 20m,
                            Name = "Espalda Alta",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000002"),
                            WidthCm = 22m,
                            XCm = 5m,
                            YCm = 5m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000009"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000008"),
                            HeightCm = 20m,
                            Name = "Pecho Central",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000002"),
                            WidthCm = 18m,
                            XCm = 7m,
                            YCm = 8m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000010"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000009"),
                            HeightCm = 28m,
                            Name = "Espalda Completa",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000001"),
                            WidthCm = 28m,
                            XCm = 4m,
                            YCm = 6m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000011"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000010"),
                            HeightCm = 18m,
                            Name = "Pecho Central",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000002"),
                            WidthCm = 16m,
                            XCm = 8m,
                            YCm = 8m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000012"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000011"),
                            HeightCm = 28m,
                            Name = "Espalda Completa",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000002"),
                            WidthCm = 28m,
                            XCm = 4m,
                            YCm = 6m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000013"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000012"),
                            HeightCm = 14m,
                            Name = "Capota",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000003"),
                            WidthCm = 18m,
                            XCm = 3m,
                            YCm = 3m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000014"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000013"),
                            HeightCm = 10m,
                            Name = "Pecho Izquierdo",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000004"),
                            WidthCm = 10m,
                            XCm = 5m,
                            YCm = 6m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000015"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000014"),
                            HeightCm = 26m,
                            Name = "Espalda Grande",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000002"),
                            WidthCm = 28m,
                            XCm = 4m,
                            YCm = 6m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000016"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000015"),
                            HeightCm = 8m,
                            Name = "Logo Manga",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000004"),
                            WidthCm = 8m,
                            XCm = 2m,
                            YCm = 4m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000017"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000016"),
                            HeightCm = 12m,
                            Name = "Muslo Derecho",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000001"),
                            WidthCm = 12m,
                            XCm = 6m,
                            YCm = 18m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000018"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000017"),
                            HeightCm = 15m,
                            Name = "Parte Trasera",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000003"),
                            WidthCm = 20m,
                            XCm = 5m,
                            YCm = 8m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000019"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000018"),
                            HeightCm = 12m,
                            Name = "Muslo Derecho",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000001"),
                            WidthCm = 12m,
                            XCm = 6m,
                            YCm = 10m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000020"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000019"),
                            HeightCm = 15m,
                            Name = "Parte Trasera",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000003"),
                            WidthCm = 20m,
                            XCm = 5m,
                            YCm = 8m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000021"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000020"),
                            HeightCm = 7m,
                            Name = "Frente Gorra",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000003"),
                            WidthCm = 10m,
                            XCm = 3m,
                            YCm = 4m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000022"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000021"),
                            HeightCm = 5m,
                            Name = "Lateral Gorra",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000004"),
                            WidthCm = 7m,
                            XCm = 2m,
                            YCm = 4m
                        },
                        new
                        {
                            Id = new Guid("d0000001-0000-0000-0000-000000000023"),
                            GarmentViewId = new Guid("c0000001-0000-0000-0000-000000000022"),
                            HeightCm = 22m,
                            Name = "Cara Frontal",
                            RecommendedTechniqueId = new Guid("a0000001-0000-0000-0000-000000000001"),
                            WidthCm = 22m,
                            XCm = 5m,
                            YCm = 8m
                        });
                });

            modelBuilder.Entity("AiWearStudio.Catalog.Domain.Entities.TenantGarmentStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GarmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "GarmentId")
                        .IsUnique()
                        .HasDatabaseName("uix_tenant_garment_status");

                    b.ToTable("tenant_garment_status", "catalog");
                });

            modelBuilder.Entity("AiWearStudio.Catalog.Domain.Entities.GarmentColorVariant", b =>
                {
                    b.HasOne("AiWearStudio.Catalog.Domain.Entities.Garment", null)
                        .WithMany("ColorVariants")
                        .HasForeignKey("GarmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiWearStudio.Catalog.Domain.Entities.GarmentView", b =>
                {
                    b.HasOne("AiWearStudio.Catalog.Domain.Entities.Garment", null)
                        .WithMany("Views")
                        .HasForeignKey("GarmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiWearStudio.Catalog.Domain.Entities.PrintZone", b =>
                {
                    b.HasOne("AiWearStudio.Catalog.Domain.Entities.GarmentView", null)
                        .WithMany("PrintZones")
                        .HasForeignKey("GarmentViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiWearStudio.Catalog.Domain.Entities.PrintTechnique", "RecommendedTechnique")
                        .WithMany()
                        .HasForeignKey("RecommendedTechniqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecommendedTechnique");
                });

            modelBuilder.Entity("AiWearStudio.Catalog.Domain.Entities.Garment", b =>
                {
                    b.Navigation("ColorVariants");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("AiWearStudio.Catalog.Domain.Entities.GarmentView", b =>
                {
                    b.Navigation("PrintZones");
                });
#pragma warning restore 612, 618
        }
    }
}
